// src/components/Banner.vue
<template>
  <section id="home" class="banner">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="txt-rotate-bounding-box">
            <div class="animate__animated animate__fadeIn">
              <span class="tagline">Welcome to my Portfolio</span>
              <h1>
                <span class="txt-rotate" data-period="1000">
                  Hi I'm Dan<span class="wrap">{{ text }}</span>
                </span>
              </h1>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="animate__animated animate__zoomIn">
            <img :src="headerImg" alt="An Ai rendition of Dan" />
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import headerImg from "../assets/img/header-img.webp";

const loopNum = ref(0);
const isDeleting = ref(false);
const text = ref("");
const delta = ref(300 - Math.random() * 100);
const period = 2000;
let timeoutId: number | undefined;

const toRotate = [
  ", Hello World!",
  ", getting more coffee",
  ", a Software Engineer",
  ", I'm trying my best",
  ", Learning as I go",
  ", I'm never giving up",
];


const tick = () => {
  const i = loopNum.value % toRotate.length;
  const fullText = toRotate[i];
  const updatedText = isDeleting.value
    ? fullText.substring(0, text.value.length - 1)
    : fullText.substring(0, text.value.length + 1);

  text.value = updatedText;

  if (isDeleting.value) {
    delta.value = delta.value / 2;
  }

  if (!isDeleting.value && updatedText === fullText) {
    isDeleting.value = true;
    delta.value = period;
  } else if (isDeleting.value && updatedText === "") {
    isDeleting.value = false;
    loopNum.value += 1;
    delta.value = 500;
  }

  timeoutId = window.setTimeout(tick, delta.value);
};

onMounted(() => {
  timeoutId = window.setTimeout(tick, delta.value);
});

onUnmounted(() => {
  if (timeoutId) {
    window.clearTimeout(timeoutId);
  }
});
</script>

// src/components/Banner.tsx
import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import headerImg from "../assets/img/header-img.webp";
import "animate.css";

export function Banner() {
  const [loopNum, setLoopNum] = React.useState(0);
  const [isDeleting, setIsDeleting] = React.useState(false);
  const [text, setText] = React.useState("");
  const [delta, setDelta] = React.useState(300 - Math.random() * 100);
  const [, setIndex] = React.useState(1);
  const period = 2000;

  /**
   * Ticks the text.
   * @returns void
   */
  const tick = React.useCallback(() => {
    const toRotate = [
      ", Hello World!",
      ", getting more coffee",
      ", a Software Engineer",
      ", I'm trying my best",
      ", Learning as I go",
      ", I'm never giving up",
    ];
    let i = loopNum % toRotate.length;
    let fullText = toRotate[i];
    let updatedText = isDeleting
      ? fullText.substring(0, text.length - 1)
      : fullText.substring(0, text.length + 1);
    setText(updatedText);

    if (isDeleting) {
      setDelta((prevDelta) => prevDelta / 2);
    }

    if (!isDeleting && updatedText === fullText) {
      setIsDeleting(true);
      setIndex((prevIndex) => prevIndex - 1);
      setDelta(period);
    } else if (isDeleting && updatedText === "") {
      setIsDeleting(false);
      setLoopNum(loopNum + 1);
      setIndex(1);
      setDelta(500);
    } else {
      setIndex((prevIndex) => prevIndex + 1);
    }
  }, [isDeleting, loopNum, text.length]);
  React.useEffect(() => {
    let ticker = setInterval(() => {
      tick();
    }, delta);

    return () => {
      clearInterval(ticker);
    };
  }, [text, delta, tick]);

  return (
    <section className="banner" id="home">
      <Container>
        <Row className="align-items-center">
          <Col xs={12} md={6} xl={7}>
            <div className="txt-rotate-bounding-box">
              <div className="animate__animated animate__fadeIn">
                <span className="tagline">Welcome to my Portfolio</span>
                <h1>
                  {``}{" "}
                  <span className="txt-rotate" data-period="1000">
                    Hi i&apos;m Dan<span className="wrap">{text}</span>
                  </span>
                </h1>
              </div>
            </div>
          </Col>
          <Col xs={12} md={6} xl={5}>
            <div className="animate__animated animate__zoomIn">
              <img src={headerImg} alt="An Ai rendition of Dan" />
            </div>
          </Col>
        </Row>
      </Container>
    </section>
  );
};
