// src/components/ProjectCard.jsx
import { Col } from "react-bootstrap";
import PropTypes from "prop-types";

export const ProjectCard = ({ title, description, imgUrl, urlJump }) => {
  return (
    <Col size={12} sm={6} md={3} className="proj-colbx">
      <a href={urlJump}><div className="proj-imgbx">
        <img src={imgUrl} alt=""/>
        <div className="proj-txtx">
          <h4>{title}</h4>
          <span>{description}</span>
        </div>
      </div></a>
    </Col>
  )
}

ProjectCard.propTypes = {
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  imgUrl: PropTypes.string.isRequired,
  urlJump: PropTypes.string.isRequired,
}

// src/components/ProjectCard.vue
<template>
  <div class="col-12 col-sm-6 col-md-3 proj-colbx">
    <a :href="props.urlJump" target="_blank" rel="noreferrer noopener">
      <div class="proj-imgbx">
        <img :src="props.imgUrl" alt="Project image" />
        <div class="proj-txtx">
          <h4>{{ props.title }}</h4>
          <span>{{ props.description }}</span>
        </div>
      </div>
    </a>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  title: string;
  description: string;
  imgUrl: string;
  urlJump: string;
}>();
</script>
