// src/components/ProjectCard.tsx
import { Col } from "react-bootstrap";

export type ProjectCardProps = {
  title: string;
  description: string;
  imgUrl: string;
  urlJump: string;
};

export function ProjectCard({
  title,
  description,
  imgUrl,
  urlJump,
}: ProjectCardProps) {
  return (
    <Col size={12} sm={6} md={3} className="proj-colbx">
      <a href={urlJump}>
        <div className="proj-imgbx">
          <img src={imgUrl} alt="" />
          <div className="proj-txtx">
            <h4>{title}</h4>
            <span>{description}</span>
          </div>
        </div>
      </a>
    </Col>
  );
};

// src/components/ProjectCard.vue
<template>
  <div class="col-12 col-sm-6 col-md-3 proj-colbx">
    <a :href="props.urlJump" target="_blank" rel="noreferrer noopener">
      <div class="proj-imgbx">
        <img :src="props.imgUrl" alt="Project image" />
        <div class="proj-txtx">
          <h4>{{ props.title }}</h4>
          <span>{{ props.description }}</span>
        </div>
      </div>
    </a>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  title: string;
  description: string;
  imgUrl: string;
  urlJump: string;
}>();
</script>
